[alias]
c = "check"
be = "build --example"
ee = "embed --example"
oe = "objcopy --example"

blinky = "be blinky"
blinky-probe = "ee blinky"
blinky-bin = "oe blinky --release -- -O binary target/thumbv7em-none-eabihf/release/examples/blinky.bin"

usb_echo = "be usb_echo"
usb_echo-probe = "ee usb_echo"
usb_echo-bin = "oe usb_echo --release -- -O binary target/thumbv7em-none-eabihf/release/examples/usb_echo.bin"

ethernet = "be ethernet --features=ethernet"
ethernet-probe = "ee ethernet --features=ethernet"
ethernet-bin = "oe ethernet --features=ethernet --release -- -O binary target/thumbv7em-none-eabihf/release/examples/ethernet.bin"

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

rustflags = [
  # Use LLD as the default linker
  "-C", "link-arg=-Tlink.x",
]
